tunnel: postgres-db
credentials-file: /home/server/.cloudflared/fc2b86a8-be5f-47c5-9d55-e604b97dd0c3.json

ingress:
  - hostname: postgres.fathul.my
    service: tcp://localhost:5432
  - service: http_status:404